### ISSUE TITLE
Unexpected token '.'

### ISSUE THREAD

**Issue by peterjurkovic** [DeepLcom/deepl-mock#1] opened 2021-11-06 07:34 UTC
Hello, can not start deepl-mock server. Could you please help? 

```
pjurkovic@pjurkovic ~/workspace/deepl-mock (main)$ npm start

> deepl-mock@1.2.0 start /home/pjurkovic/workspace/deepl-mock
> DEEPL_MOCK_SERVER_PORT=3000 node index.js

/home/pjurkovic/workspace/deepl-mock/index.js:37
  if (options?.params) {
              ^

SyntaxError: Unexpected token '.'
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deepl-mock@1.2.0 start: `DEEPL_MOCK_SERVER_PORT=3000 node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deepl-mock@1.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Is there a docker image available?

**Comment by ghost** [comment] 2021-11-08 09:40
Hi @peterjurkovic , thanks for reporting the issue. We don't have a docker image available at the moment.

The issue might be caused by the `node` version: I was able to reproduce this issue with node v12 and node v13, and the issue is resolved with node **v14**. Although we do not yet have a dedicated docker image available, you could try using the `node:14` docker image, with a command like the following:

`docker run --volume $(pwd):/app --workdir /app -p 3000:0000 --env DEEPL_MOCK_SERVER_PORT=3000 node:14 node index.js`

**Comment by ghost** [comment] 2022-01-21 11:10
Hello again. As of v1.3.1, a Dockerfile is included to simplify building a Docker image:
https://github.com/DeepLcom/deepl-mock/blob/v1.3.1/README.md#using-docker

**Closed as completed by ghost** 2022-01-21 11:10 UTC
